apiVersion: v1
kind: Service
metadata:
  name: myngnix
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30777
---	  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myngnix
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      
      containers:
      - name: c001
        image: ngnix
        ports:
        - containerPort: 80
          

